export const SRI_LANKAN_BANKS = [
  "Amana Bank",
  "Bank of Ceylon (BOC)",
  "Bank of India",
  "Cargills Bank",
  "Citibank N.A.",
  "Commercial Bank of Ceylon",
  "Deutsche Bank",
  "DFCC Bank",
  "Habib Bank",
  "Hatton National Bank (HNB)",
  "Housing Development Finance Corporation Bank (HDFC)",
  "HSBC",
  "Indian Bank",
  "Indian Overseas Bank",
  "MCB Bank",
  "Merchant Bank of Sri Lanka & Finance",
  "National Development Bank (NDB)",
  "National Savings Bank (NSB)",
  "Nations Trust Bank (NTB)",
  "Pan Asia Banking Corporation",
  "People's Bank",
  "Regional Development Bank (RDB)",
  "Sampath Bank",
  "Seylan Bank",
  "Standard Chartered Bank",
  "State Mortgage & Investment Bank",
  "Union Bank of Colombo",
];
